# Generated by Django 4.2.7 on 2024-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_foydalanuvchilar_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('body', models.CharField(max_length=200, verbose_name='Asl narxi')),
                ('new', models.CharField(max_length=200, verbose_name='Aksiyadagi narx')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
