# Generated by Django 4.2.7 on 2024-01-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Market',
        ),
    ]
