# Generated by Django 4.2.7 on 2024-01-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_market_rangi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='titles',
        ),
    ]
