# Generated by Django 4.2.6 on 2025-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_order_total_price_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sklad',
            field=models.CharField(default=False, max_length=455, null=True, verbose_name="Savatga qo'shilganmi"),
        ),
    ]
