# Generated by Django 4.2.7 on 2024-01-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_title_category_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='new',
        ),
        migrations.AddField(
            model_name='market',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Davlati'),
        ),
        migrations.AddField(
            model_name='market',
            name='holati',
            field=models.CharField(max_length=200, null=True, verbose_name='holati'),
        ),
        migrations.AddField(
            model_name='market',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='market',
            name='tell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='market',
            name='body',
            field=models.CharField(max_length=200, null=True, verbose_name='Asl narxi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='rangi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Markasi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Mahsulot nomi'),
        ),
    ]
