# Generated by Django 4.2.6 on 2025-01-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_order_sklad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='aborud',
            name='bbm',
        ),
        migrations.RemoveField(
            model_name='mahsulotlar',
            name='bbm',
        ),
        migrations.RemoveField(
            model_name='market',
            name='bbm',
        ),
        migrations.RemoveField(
            model_name='seryo',
            name='bbm',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
