# Generated by Django 4.2.7 on 2024-01-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_market_new_market_country_market_holati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aborud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Mashinani rasmi')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('holati', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
