# Generated by Django 4.2.7 on 2024-01-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aborud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aborud',
        ),
    ]
