# Generated by Django 4.2.6 on 2025-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_buyurtma'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='umumiy_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
