# Generated by Django 4.2.6 on 2025-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_buyurtma_umumiy_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='foydalanuvchi_kiritgan_kg',
            field=models.JSONField(default=dict, verbose_name='Foydalanuvchi kilogrammi'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='umumiy_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy kilogramm'),
        ),
    ]
