# Generated by Django 4.2.6 on 2025-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_buyurtma_foydalanuvchi_kiritgan_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Zakaz nomi')),
                ('body', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
                ('tasdiqlandi', models.BooleanField(default=False, verbose_name='Tasdiqlanganmi')),
            ],
        ),
    ]
