# Generated by Django 4.2.6 on 2024-02-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_market_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aborud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Mashinani nomi')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('holati', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=200, null=True, verbose_name='Narxi')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Mahsulot nomi')),
                ('qalinligi', models.CharField(max_length=200, null=True, verbose_name='Mahsulotni qalinligi')),
                ('razmeri', models.CharField(max_length=200, null=True, verbose_name='Mahsulotni razmeri')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('body', models.CharField(max_length=200, null=True, verbose_name='Narxi')),
                ('rangi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.market', verbose_name='Markasi')),
            ],
        ),
    ]
