# Generated by Django 4.2.6 on 2025-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_zakaz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zakaz',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='tasdiqlandi',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlanganmi'),
        ),
    ]
