# Generated by Django 4.2.7 on 2024-02-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_aborud_mahsulotlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='rangi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Rangi'),
        ),
    ]
