# Generated by Django 5.1.4 on 2025-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_zakaz_buyurtma_tasdiqlandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='aborud',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz'), ('en', 'en')], default='uz', max_length=100),
        ),
        migrations.AddField(
            model_name='mahsulotlar',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz'), ('en', 'en')], default='uz', max_length=100),
        ),
        migrations.AddField(
            model_name='market',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz'), ('en', 'en')], default='uz', max_length=100),
        ),
        migrations.AddField(
            model_name='seryo',
            name='group_lang',
            field=models.CharField(choices=[('ru', 'ru'), ('uz', 'uz'), ('en', 'en')], default='uz', max_length=100),
        ),
    ]
