# Generated by Django 4.2.6 on 2024-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_market_rangi'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Saqlangan'),
        ),
    ]
