# Generated by Django 5.1.4 on 2025-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_aborud_group_lang_mahsulotlar_group_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aborud',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='mahsulotlar',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='seryo',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=100),
        ),
    ]
