# Generated by Django 4.2.6 on 2024-02-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_market_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Mahsulot nomi')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('body', models.CharField(max_length=200, null=True, verbose_name='Narxi')),
                ('markasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.market', verbose_name='Markasi')),
            ],
        ),
    ]
