# Generated by Django 4.2.6 on 2024-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_seryo'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='korzina',
            field=models.BooleanField(default=False, verbose_name='korzina'),
        ),
    ]
