# Generated by Django 4.2.7 on 2024-02-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_market_korzina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='korzina',
            new_name='sklad',
        ),
    ]
