# Generated by Django 4.2.6 on 2025-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_mahsulotlar_rangi_alter_aborud_group_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aborud',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('en', 'en'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='mahsulotlar',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('en', 'en'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('en', 'en'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='seryo',
            name='group_lang',
            field=models.CharField(choices=[('uz', 'uz'), ('en', 'en'), ('ru', 'ru')], default='uz', max_length=100),
        ),
        migrations.AlterField(
            model_name='seryo',
            name='markasi',
            field=models.CharField(max_length=200, null=True, verbose_name='Markasi'),
        ),
    ]
